// Generated by CoffeeScript 1.4.0
(function() {
  var ready;

  ready = function(func) {
    "Hacky $(document).ready() equivalent.";
    if (/in/.test(document.readyState)) {
      return setTimeout(ready, 9, func);
    } else {
      return func();
    }
  };

  ready(function() {
    var canvas, ctx, draw, x, y;
    canvas = document.getElementById('canvas');
    ctx = canvas.getContext('2d');
    canvas.setAttribute('width', window.innerWidth);
    canvas.setAttribute('height', window.innerHeight);
    ctx.strokeStyle = "rgb(255,255,255)";
    x = window.innerWidth / 2;
    y = window.innerHeight / 2;
    draw = function() {
      var angle, now, pareto, x1, y1;
      now = Date.now();
      angle = Math.random() * 2 * Math.PI;
      pareto = Math.pow(Math.random(), -1 / 1.5);
      x1 = x + Math.cos(angle) * pareto * 5;
      y1 = y + Math.sin(angle) * pareto * 5;
      ctx.beginPath();
      ctx.moveTo(x, y);
      ctx.lineTo(x1, y1);
      ctx.stroke();
      x = x1;
      y = y1;
      return setTimeout(draw, 50);
    };
    return draw();
  });

}).call(this);
